In [2]:
import pandas as pd

IMPORT DATA

In [3]:
ratings=pd.read_csv('ratings.csv')
reviews=pd.read_csv('reviews.csv')
titles=pd.read_csv('titles.csv')
subscribers=pd.read_csv('subscribers.csv')
watch_history=pd.read_csv('watch_history.csv')
watchlist=pd.read_csv('watchlist.csv')

RATINGS TABLE CLEANING

In [4]:
ratings.isnull().sum()

rating_id        0
subscriber_id    0
title_id         0
rating           0
rating_date      0
dtype: int64

In [5]:
ratings.duplicated().sum()

np.int64(0)

In [6]:
ratings.duplicated().sum()

np.int64(0)

In [7]:
ratings.dtypes

rating_id        int64
subscriber_id      str
title_id           str
rating           int64
rating_date        str
dtype: object

In [8]:
ratings["rating_date"] = pd.to_datetime(ratings["rating_date"])

REVIEWS TABLE CLEANING

In [9]:
reviews.isnull().sum()

review_id        0
subscriber_id    0
title_id         0
review_text      0
sentiment        0
helpful_votes    0
review_date      0
dtype: int64

In [10]:
reviews.duplicated().sum()

np.int64(0)

In [11]:
reviews.dtypes

review_id        int64
subscriber_id      str
title_id           str
review_text        str
sentiment          str
helpful_votes    int64
review_date        str
dtype: object

In [12]:
reviews["review_date"] = pd.to_datetime(reviews["review_date"])

In [13]:
reviews

,review_id,subscriber_id,title_id,review_text,sentiment,helpful_votes,review_date
0,1,SUB102409,TTL206425,Stellar cast and a satisfying ending.,Positive,9,2023-11-04
1,2,SUB111270,TTL203987,Predictable plot and flat characters.,Negative,4,2026-04-25
2,3,SUB107848,TTL203235,"Started strong, lost steam in the middle.",Neutral,2,2024-07-31
3,4,SUB114501,TTL200930,Beautifully shot and emotionally resonant.,Positive,14,2022-12-13
4,5,SUB113370,TTL207141,A rare gem. Highly recommend.,Positive,6,2025-10-09
...,...,...,...,...,...,...,...
109995,109996,SUB100390,TTL207141,Average. Worth it if you like the genre.,Neutral,3,2025-05-31
109996,109997,SUB114968,TTL208918,Disappointing given the hype.,Negative,4,2025-12-03
109997,109998,SUB112680,TTL205235,A rare gem. Highly recommend.,Positive,6,2024-10-05
109998,109999,SUB107694,TTL202380,"Good for a quiet evening, fairly forgettable.",Neutral,6,2026-05-18
109999,110000,SUB103058,TTL201978,The writing is sharp and the pacing is perfect.,Positive,7,2026-05-22

SUBSCRIBERS TABLE CLEANING

In [14]:
subscribers.isnull().sum()

subscriber_id            0
signup_date              0
country                  0
region                   0
age                      0
gender                   0
plan_type                0
monthly_price_usd        0
household_size           0
primary_device           0
payment_method           0
tenure_months            0
is_active                0
churn_date           11199
dtype: int64

In [15]:
subscribers['is_active'] = subscribers['is_active'].astype(str).str.strip().str.upper().map({
    'TRUE':'Active',
    'FALSE':'Inactive',
    '1':'Active',
    '0':'Inactive'
})

In [16]:
titles.isna()

,title_id,title_name,type,primary_genre,country,language,release_year,date_added,maturity_rating,seasons,...,is_original,license_type,director,cast,quality_score,popularity_score,license_cost_usd,license_expiry,total_watch_hours,total_plays
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
8999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

TITLES TABLE CLEANING

In [17]:
titles.duplicated().sum()

np.int64(0)

In [18]:
titles.isnull().sum()

title_id                   0
title_name                 0
type                       0
primary_genre              0
country                    0
language                   0
release_year               0
date_added                 0
maturity_rating            0
seasons                    0
content_duration_min       0
is_original                0
license_type               0
director                   0
cast                       0
quality_score              0
popularity_score           0
license_cost_usd           0
license_expiry          1966
total_watch_hours          0
total_plays                0
dtype: int64

In [19]:
titles['date_added'] = pd.to_datetime(titles['date_added'], errors='coerce')
titles['license_expiry'] = pd.to_datetime(titles['license_expiry'], errors='coerce')

In [20]:
titles.dtypes

title_id                           str
title_name                         str
type                               str
primary_genre                      str
country                            str
language                           str
release_year                     int64
date_added              datetime64[us]
maturity_rating                    str
seasons                          int64
content_duration_min             int64
is_original                       bool
license_type                       str
director                           str
cast                               str
quality_score                  float64
popularity_score               float64
license_cost_usd                 int64
license_expiry          datetime64[us]
total_watch_hours              float64
total_plays                      int64
dtype: object

CLEANING WATCH_HISTORY TABLE

In [21]:
watch_history.isnull().sum()

watch_id                0
subscriber_id           0
title_id                0
watch_date              0
device                  0
region                  0
content_duration_min    0
watch_duration_min      0
completion_pct          0
completed               0
dtype: int64

In [22]:
watch_history.duplicated().sum()

np.int64(0)

In [23]:
watch_history.dtypes

watch_id                  int64
subscriber_id               str
title_id                    str
watch_date                  str
device                      str
region                      str
content_duration_min      int64
watch_duration_min      float64
completion_pct          float64
completed                   str
dtype: object

In [24]:
watch_history["watch_date"] = pd.to_datetime(watch_history["watch_date"])

In [25]:
watch_history['completed'] = watch_history['completed'].astype(str).str.strip().str.lower().map({
    'true':'Completed',
    'false':'Not Completed',
    '1':'Completed',
    '0':'Not Completed'
})

In [26]:
watch_history

,watch_id,subscriber_id,title_id,watch_date,device,region,content_duration_min,watch_duration_min,completion_pct,completed
0,1,SUB107630,TTL205207,2024-01-01,Smart TV,East Asia,888,826.7,93.1,NaN
1,2,SUB114773,TTL204889,2025-10-18,Mobile,South Asia,2340,1866.4,79.8,NaN
2,3,SUB106013,TTL206882,2026-04-26,Mobile,Latin America,656,75.0,11.4,NaN
3,4,SUB100939,TTL208849,2026-03-09,Mobile,North America,500,493.2,98.6,NaN
4,5,SUB107223,TTL202529,2023-12-27,Tablet,North America,141,94.6,67.1,NaN
...,...,...,...,...,...,...,...,...,...,...
649995,649996,SUB113946,TTL207486,2025-07-13,Mobile,Europe,444,8.6,1.9,NaN
649996,649997,SUB108172,TTL200072,2026-05-22,Smart TV,Latin America,420,338.3,80.5,NaN
649997,649998,SUB108092,TTL204011,2025-01-25,Streaming Stick,South Asia,261,47.4,18.2,NaN
649998,649999,SUB114820,TTL204762,2026-04-13,Tablet,North America,77,11.6,15.0,NaN
649999,650000,SUB101592,TTL206202,2022-10-16,Game Console,Latin America,61,29.4,48.2,NaN

WATCHLIST TABLE CLEANING

In [27]:
watchlist.isnull().sum()

watchlist_id     0
subscriber_id    0
title_id         0
added_date       0
watched          0
dtype: int64

In [28]:
watchlist.duplicated().sum()

np.int64(0)

In [29]:
watchlist.dtypes

watchlist_id     int64
subscriber_id      str
title_id           str
added_date         str
watched            str
dtype: object

In [30]:
watchlist["added_date"] = pd.to_datetime(watchlist["added_date"])

In [31]:
watchlist['watched'] = watchlist['watched'].map({
    True: 'Watched',
    False: 'Not Watched'
})

In [32]:
watchlist["watched"].unique()

<StringArray>
[nan]
Length: 1, dtype: str

In [33]:
watchlist.duplicated(subset=['subscriber_id','title_id']).sum()

np.int64(61)

In [36]:
ratings.to_csv('ratings.csv', index=False)
reviews.to_csv('reviews.csv', index=False)
titles.to_csv('titles.csv', index=False)
subscribers.to_csv('subscribers.csv', index=False)
watch_history.to_csv('watch_history.csv', index=False)
watchlist.to_csv('watchlist.csv', index=False)

In [35]:
ratings.dtypes

rating_id                 int64
subscriber_id               str
title_id                    str
rating                    int64
rating_date      datetime64[us]
dtype: object